@startuml SampleERD
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

class Class {
    PK : Class ID
    FK : Student ID
    --
    Class name
    Class Description
}

class Student {
    PK : Entity ID
    --
    First Name
    Last Name
    Date of birth
    Mark
    Class
}
note right: Entity / Table

note right of Student::"PK : Entity ID"
    Unique ID / Key
end note

note right of Student::"First Name"
    Fields / Attributes
end note

note as NoteFloat01
    This is a note connected to
    an entity with no relationship.
end note

note as NoteFloat02
    This is a note
    connecting 2 entities...
end note

Student .. NoteFloat02
NoteFloat02 .. Class

NoteFloat01 .. Entity

Student |o--{ Class

@enduml
